#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#    May 27, 2020 05:37:29 PM CEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import LauncherWindow_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    LauncherWindow_support.set_Tk_var()
    top = Toplevel1 (root)
    import Launcher as FFF
    FFF.link_with_gui(root, top)
    LauncherWindow_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    LauncherWindow_support.set_Tk_var()
    top = Toplevel1 (w)
    LauncherWindow_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 

        top.geometry("559x260+1084+535")
        top.title("SFlyFF Server Starter")
        top.configure(relief="ridge")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Labelframe1 = tk.LabelFrame(top)
        self.Labelframe1.place(relx=0.465, rely=0.038, relheight=0.558
                , relwidth=0.501)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''Server''')
        self.Labelframe1.configure(background="#d9d9d9")
        self.Labelframe1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1.configure(highlightcolor="black")
        self.Labelframe1.configure(width=280)

        self.ServState01 = tk.Message(self.Labelframe1)
        self.ServState01.place(relx=0.143, rely=0.138, relheight=0.159
                , relwidth=0.786, bordermode='ignore')
        self.ServState01.configure(background="#d9d9d9")
        self.ServState01.configure(foreground="#000000")
        self.ServState01.configure(highlightbackground="#d9d9d9")
        self.ServState01.configure(highlightcolor="black")
        self.ServState01.configure(text='''Message''')
        self.ServState01.configure(width=220)

        self.ServCbx01 = tk.Checkbutton(self.Labelframe1)
        self.ServCbx01.place(relx=0.036, rely=0.138, relheight=0.172
                , relwidth=0.075, bordermode='ignore')
        self.ServCbx01.configure(activebackground="#d9d9d9")
        self.ServCbx01.configure(activeforeground="#000000")
        self.ServCbx01.configure(background="#d9d9d9")
        self.ServCbx01.configure(disabledforeground="#a3a3a3")
        self.ServCbx01.configure(foreground="#000000")
        self.ServCbx01.configure(highlightbackground="#d9d9d9")
        self.ServCbx01.configure(highlightcolor="black")
        self.ServCbx01.configure(justify='left')
        self.ServCbx01.configure(variable=LauncherWindow_support.ServC1)

        self.ServStart_1 = tk.Button(self.Labelframe1)
        self.ServStart_1.place(relx=0.036, rely=0.414, height=34, width=257
                , bordermode='ignore')
        self.ServStart_1.configure(activebackground="#ececec")
        self.ServStart_1.configure(activeforeground="#000000")
        self.ServStart_1.configure(background="#d9d9d9")
        self.ServStart_1.configure(disabledforeground="#a3a3a3")
        self.ServStart_1.configure(foreground="#000000")
        self.ServStart_1.configure(highlightbackground="#d9d9d9")
        self.ServStart_1.configure(highlightcolor="black")
        self.ServStart_1.configure(pady="0")
        self.ServStart_1.configure(text='''Start Server''')

        self.ServStart_2 = tk.Button(self.Labelframe1)
        self.ServStart_2.place(relx=0.036, rely=0.69, height=34, width=257
                , bordermode='ignore')
        self.ServStart_2.configure(activebackground="#ececec")
        self.ServStart_2.configure(activeforeground="#000000")
        self.ServStart_2.configure(background="#d9d9d9")
        self.ServStart_2.configure(disabledforeground="#a3a3a3")
        self.ServStart_2.configure(foreground="#000000")
        self.ServStart_2.configure(highlightbackground="#d9d9d9")
        self.ServStart_2.configure(highlightcolor="black")
        self.ServStart_2.configure(pady="0")
        self.ServStart_2.configure(text='''Stop Server''')

        self.Labelframe2 = tk.LabelFrame(top)
        self.Labelframe2.place(relx=0.018, rely=0.038, relheight=0.942
                , relwidth=0.429)
        self.Labelframe2.configure(relief='groove')
        self.Labelframe2.configure(foreground="black")
        self.Labelframe2.configure(text='''Client''')
        self.Labelframe2.configure(background="#d9d9d9")
        self.Labelframe2.configure(highlightbackground="#d9d9d9")
        self.Labelframe2.configure(highlightcolor="black")
        self.Labelframe2.configure(width=240)

        self.ClientState2 = tk.Message(self.Labelframe2)
        self.ClientState2.place(relx=0.042, rely=0.204, relheight=0.094
                , relwidth=0.917, bordermode='ignore')
        self.ClientState2.configure(background="#d9d9d9")
        self.ClientState2.configure(foreground="#000000")
        self.ClientState2.configure(highlightbackground="#d9d9d9")
        self.ClientState2.configure(highlightcolor="black")
        self.ClientState2.configure(text='''Message''')
        self.ClientState2.configure(width=220)

        self.ClientStartBig = tk.Button(self.Labelframe2)
        self.ClientStartBig.place(relx=0.042, rely=0.49, height=34, width=217
                , bordermode='ignore')
        self.ClientStartBig.configure(activebackground="#ececec")
        self.ClientStartBig.configure(activeforeground="#000000")
        self.ClientStartBig.configure(background="#d9d9d9")
        self.ClientStartBig.configure(disabledforeground="#a3a3a3")
        self.ClientStartBig.configure(foreground="#000000")
        self.ClientStartBig.configure(highlightbackground="#d9d9d9")
        self.ClientStartBig.configure(highlightcolor="black")
        self.ClientStartBig.configure(pady="0")
        self.ClientStartBig.configure(text='''Start''')

        self.ClientKill = tk.Button(self.Labelframe2)
        self.ClientKill.place(relx=0.042, rely=0.816, height=34, width=217
                , bordermode='ignore')
        self.ClientKill.configure(activebackground="#ececec")
        self.ClientKill.configure(activeforeground="#000000")
        self.ClientKill.configure(background="#d9d9d9")
        self.ClientKill.configure(disabledforeground="#a3a3a3")
        self.ClientKill.configure(foreground="#000000")
        self.ClientKill.configure(highlightbackground="#d9d9d9")
        self.ClientKill.configure(highlightcolor="black")
        self.ClientKill.configure(pady="0")
        self.ClientKill.configure(text='''Kill all''')

        self.ClientUpdate = tk.Button(self.Labelframe2)
        self.ClientUpdate.place(relx=0.042, rely=0.653, height=34, width=217
                , bordermode='ignore')
        self.ClientUpdate.configure(activebackground="#ececec")
        self.ClientUpdate.configure(activeforeground="#000000")
        self.ClientUpdate.configure(background="#d9d9d9")
        self.ClientUpdate.configure(disabledforeground="#a3a3a3")
        self.ClientUpdate.configure(foreground="#000000")
        self.ClientUpdate.configure(highlightbackground="#d9d9d9")
        self.ClientUpdate.configure(highlightcolor="black")
        self.ClientUpdate.configure(pady="0")
        self.ClientUpdate.configure(text='''Kill and Update''')

        self.ClientState = tk.Message(self.Labelframe2)
        self.ClientState.place(relx=0.042, rely=0.082, relheight=0.094
                , relwidth=0.917, bordermode='ignore')
        self.ClientState.configure(background="#d9d9d9")
        self.ClientState.configure(foreground="#000000")
        self.ClientState.configure(highlightbackground="#d9d9d9")
        self.ClientState.configure(highlightcolor="black")
        self.ClientState.configure(text='''Message''')
        self.ClientState.configure(width=220)

        self.ClientIni = tk.Button(self.Labelframe2)
        self.ClientIni.place(relx=0.042, rely=0.327, height=34, width=217
                , bordermode='ignore')
        self.ClientIni.configure(activebackground="#ececec")
        self.ClientIni.configure(activeforeground="#000000")
        self.ClientIni.configure(background="#d9d9d9")
        self.ClientIni.configure(disabledforeground="#a3a3a3")
        self.ClientIni.configure(foreground="#000000")
        self.ClientIni.configure(highlightbackground="#d9d9d9")
        self.ClientIni.configure(highlightcolor="black")
        self.ClientIni.configure(pady="0")
        self.ClientIni.configure(text='''Open Ini File''')

        self.Message1 = tk.Message(top)
        self.Message1.place(relx=0.751, rely=0.808, relheight=0.127
                , relwidth=0.215)
        self.Message1.configure(background="#d9d9d9")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(justify='center')
        self.Message1.configure(text='''SFlyFF Server Starter
SquonK, 2020''')
        self.Message1.configure(width=120)

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.OpenFlyFFDir = tk.Button(top)
        self.OpenFlyFFDir.place(relx=0.465, rely=0.654, height=34, width=147)
        self.OpenFlyFFDir.configure(activebackground="#ececec")
        self.OpenFlyFFDir.configure(activeforeground="#000000")
        self.OpenFlyFFDir.configure(background="#d9d9d9")
        self.OpenFlyFFDir.configure(disabledforeground="#a3a3a3")
        self.OpenFlyFFDir.configure(foreground="#000000")
        self.OpenFlyFFDir.configure(highlightbackground="#d9d9d9")
        self.OpenFlyFFDir.configure(highlightcolor="black")
        self.OpenFlyFFDir.configure(pady="0")
        self.OpenFlyFFDir.configure(text='''Open Directory''')

        self.GitButton = tk.Button(top)
        self.GitButton.place(relx=0.465, rely=0.808, height=34, width=147)
        self.GitButton.configure(activebackground="#ececec")
        self.GitButton.configure(activeforeground="#000000")
        self.GitButton.configure(background="#d9d9d9")
        self.GitButton.configure(disabledforeground="#a3a3a3")
        self.GitButton.configure(foreground="#000000")
        self.GitButton.configure(highlightbackground="#d9d9d9")
        self.GitButton.configure(highlightcolor="black")
        self.GitButton.configure(pady="0")
        self.GitButton.configure(text='''Git Bash''')

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#f9f9f9")
        Popupmenu1.configure(activeborderwidth="1")
        Popupmenu1.configure(activeforeground="black")
        Popupmenu1.configure(background="#d9d9d9")
        Popupmenu1.configure(borderwidth="1")
        Popupmenu1.configure(disabledforeground="#a3a3a3")
        Popupmenu1.configure(font="{Segoe UI} 9")
        Popupmenu1.configure(foreground="black")
        Popupmenu1.post(event.x_root, event.y_root)

if __name__ == '__main__':
    vp_start_gui()





